import { Officer } from './types';

export const OFFICER_DATA: Officer[] = [
  { id: 'cg-2', category: 'Comando', unit: 'GCG', rank: 'MAJ', matricula: '117528', name: 'ADEILSON LINS DE CARVALHO', role: 'Chefe de Gabinete do Comandante Geral c/c Chefe da Assessoria do Comandante Geral', contact: '8823-8269' },
  { id: 'ser-2', category: 'Sertão', unit: 'CPRS', rank: 'TC', matricula: '1200712', name: 'ADEMAR SIQUEIRA DA SILVA NETO', role: 'Subcomandante do Comando de Policiamento da Região Sertão', contact: '98833-4013' },
  { id: 'nzm-7', category: 'Norte/ZM', unit: '14º BPM', rank: 'MAJ', matricula: '117609', name: 'ADRIANO LEVY MONTEIRO SANTOS', role: 'Comandante do 14º BPM – Joaquim Gomes', contact: '99909-2449' },
  { id: 'nzm-5', category: 'Norte/ZM', unit: '6º BPM', rank: 'TC', matricula: '1207113', name: 'ALEANDRO FERREIRA CAITANO', role: 'Comandante do 6º BPM – Maragogi', contact: '99915-8301' },
  { id: 'nzm-2', category: 'Norte/ZM', unit: 'CPRN-ZM', rank: 'TC', matricula: '82145', name: 'ALEX HIAS ANDRADE', role: 'Subcomandante do Policiamento da Região Norte e Zona da Mata', contact: '99633-7373' },
  { id: 'esp-8', category: 'Especializado', unit: 'BPRv', rank: 'MAJ', matricula: '120758', name: 'ALEXANDRE MARTINS BISPO', role: 'Subcomandante do BPRv', contact: '99353-7117' },
  { id: 'm-2', category: 'Metropolitana', unit: 'CPM', rank: 'MAJ', matricula: '9865662', name: 'ALUCHAM ARAUJO FONSECA DE SENA', role: 'Subcomandante do Policiamento Metropolitano', contact: '98827-0303' },
  { id: 'agr-1', category: 'Agreste', unit: 'CPRA', rank: 'TC', matricula: '113743', name: 'ANAXIMANDRO TENORIO DE SA', role: 'Comandante do Poliamento da Região do Agreste', contact: '99811-4222' },
  { id: 'm-13', category: 'Metropolitana', unit: '12º BPM', rank: 'CAP', matricula: '1200674', name: 'ANDERSON LUIZ CALHEIROS OLIVEIRA', role: 'Chefe do Presídio Militar  12º BPM (PRESÍDIO)', contact: '98892-5813' },
  { id: 'cg-4', category: 'Comando', unit: 'GCG', rank: 'CAP', matricula: '337293', name: 'ANDRE LUIS SOUZA DE FIGUEIROA', role: 'Subchefe de Gabinete  do Comandante Geral', contact: '988553175' },
  { id: 'agr-5', category: 'Agreste', unit: '10º BPM', rank: 'MAJ', matricula: '1200631', name: 'ANTONIO ANDRE ANDRADE DE OLIVEIRA BARBOS', role: 'Comandante do 10º BPM – Palmeira dos Índios', contact: '99969-6894' },
  { id: 'nzm-8', category: 'Norte/ZM', unit: '14º BPM', rank: 'MAJ', matricula: '1206770', name: 'ANTONIO FURTUNATO DA SILVA', role: 'Subcomandante do 14º BPM', contact: '99156-4038' },
  { id: 'sul-9', category: 'Sul', unit: '10ª CPM/I', rank: 'MAJ', matricula: '1206850', name: 'ANTONIO HENRIQUE DIAS COSTA', role: 'Comandante da 10ª CPM/I –Teotônio Vilela. (NOVO)', contact: '99694-8206' },
  { id: 'mis-2', category: 'Missões', unit: 'CME', rank: 'TC', matricula: '121053', name: 'ANTONIO JORGE MOREIRA JUNIOR', role: 'Subcomandante do Comando de Missões Especiais', contact: '99663-7778' },
  { id: 'esc-2', category: 'Diretorias', unit: 'DEIP', rank: 'MAJ', matricula: '121100', name: 'ANTONIO UMBELINO DOS SANTOS FILHO', role: 'Subdiretor de Ensino, Instrução e Pesquisa', contact: '98858-7495' },
  { id: 'cg-6', category: 'Comando', unit: 'GCG', rank: 'TC', matricula: '121126', name: 'ARLAN SIQUEIRA DE BARROS', role: 'Chefe da SPP', contact: '99645-3134' },
  { id: 'm-19', category: 'Metropolitana', unit: '4ª CPM/I', rank: '1º TEN', matricula: '13706', name: 'AUDERAN VIRTUOSO BISPO', role: 'Subcomandante da 4ª CPM/I', contact: '99194-8203' },
  { id: 'esc-6', category: 'Diretorias', unit: 'CPM-Int', rank: 'MAJ', matricula: '1207580', name: 'BRUNO EUCLIDES DOS SANTOS OLIVEIRA', role: 'Subcomandante do Colégio da Polícia Militar do Interior', contact: '98895-0206' },
  { id: 'emg-1', category: 'EMG', unit: 'EMG', rank: 'CEL', matricula: '89346', name: 'CARLOS ALBERTO LUNA DOS SANTOS', role: 'Chefe do EMG', contact: '99318-9412' },
  { id: 'agr-3', category: 'Agreste', unit: '3º BPM', rank: 'TC', matricula: '1206869', name: 'CARLOS ALBERTO MUNIZ DE ALBUQUERQUE', role: 'Comadante do 3º BPM – Arapiraca', contact: '98833-3866' },
  { id: 'dir-11', category: 'Diretorias', unit: 'APMSAM', rank: 'CEL', matricula: '113522', name: 'CARLOS JOSE AZEVEDO SANTOS', role: 'Comandante da APMSAM', contact: '99983-3046' },
  { id: 'nzm-10', category: 'Norte/ZM', unit: '8ª CPM/I', rank: '1º TEN', matricula: '442455', name: 'CHARLANDISON RODRIGUES DOS SANTOS - 92', role: 'Subcomandante da 8ª CPM/I', contact: '99182-4791' },
  { id: 'emg-3', category: 'EMG', unit: 'EMG', rank: 'TC', matricula: '117595', name: 'CICERO SERCUNDINO DA SILVA', role: 'Chefe da 1ª Seção do EMG', contact: '99120-0867' },
  { id: 'm-17', category: 'Metropolitana', unit: '2ª CPM/I', rank: 'CAP', matricula: '98664298', name: 'CINIRA RAMOS DE FREITAS - 56', role: 'Subcomandante da 2ª CPM/I', contact: '98841-1041' },
  { id: 'agr-8', category: 'Agreste', unit: '3ª CPM/I', rank: '1º TEN', matricula: '1732', name: 'CLAUDIO HENRIQUE SANTOS DO CARMO', role: 'Subcomandante da 3ª CPM/I', contact: '99951-7977' },
  { id: 'cor-2', category: 'Administrativo', unit: 'CORREG', rank: 'TC', matricula: '102784', name: 'CLAUDIO JOSE DA SILVA', role: 'Subcorregedor Geral', contact: '99157-7657' },
  { id: 'mis-13', category: 'Missões', unit: 'CPM/I-RAIO', rank: 'CAP', matricula: '499013', name: 'DANIEL PITA AMARAL', role: 'Comandante da CPM/I-RAIO', contact: '98894-1367' },
  { id: 'dir-13', category: 'Diretorias', unit: 'CFAP', rank: 'MAJ', matricula: '117722', name: 'DANIEL SAMPAIO VALOES DA ROCHA', role: 'Comandante do CFAP', contact: '99998-9994' },
  { id: 'm-14', category: 'Metropolitana', unit: '13º BPM', rank: 'MAJ', matricula: '1206893', name: 'DANIEL SOUZA DOS SANTOS', role: 'Comandante do 13º BPM – Jacintinho', contact: '99928-2939' },
  { id: 'cg-5', category: 'Comando', unit: 'GCG', rank: 'MAJ', matricula: '1206842', name: 'DAVID DELEON LOPES DA SILVA', role: 'Chefe da SPO', contact: '98867-7861' },
  { id: 'mis-7', category: 'Missões', unit: 'RPMon', rank: 'TC', matricula: '1207318', name: 'DIEGO HENRIQUE BEZERRA VIEIRA', role: 'Comandante do RPMon', contact: '99644-8691' },
  { id: 'mis-3', category: 'Missões', unit: 'BOPE', rank: 'TC', matricula: '---', name: 'DIEGO SARMENTO FIRMINO', role: 'Comandante do BOPE', contact: '99973-3680' },
  { id: 'mis-8', category: 'Missões', unit: 'RPMon', rank: 'CAP', matricula: '98653296', name: 'DIOGO BUARQUE PEREIRA', role: 'Subcomandante do RPMon', contact: '99608-7294' },
  { id: 'agr-2', category: 'Agreste', unit: 'CPRA', rank: 'TC', matricula: '120766', name: 'DIOGO VITAL DE OLIVEIRA', role: 'Subcomandante do Poliamento da Região do Agreste', contact: '99902-0896' },
  { id: 'ser-7', category: 'Sertão', unit: '6ª CPM/I', rank: 'CAP', matricula: '1643', name: 'EDUARDO HENRIQUE SALUSTIANO SANTOS', role: 'Comandante da 6ª CPM/I – Batalha. (NOVO)', contact: '99835-0637' },
  { id: 'agr-4', category: 'Agreste', unit: '3º BPM', rank: 'CAP', matricula: '1207474', name: 'EMANOEL PEDRO SANTOS SILVA', role: 'Subcomandante do 3º BPM', contact: '99900-7800' },
  { id: 'dir-2', category: 'Diretorias', unit: 'PMAL', rank: 'TC', matricula: '117641', name: 'EMERSON CAMARA DE CASTRO', role: 'Subdiretor de Finanças', contact: '99393-8959' },
  { id: 'cg-14', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'MAJ', matricula: '120421', name: 'EURICO CORREIA LEAL', role: 'Chefe da Seção de Serviço de Informações ao Cidadão da Ouvidoria Geral', contact: '98855-0898' },
  { id: 'm-15', category: 'Metropolitana', unit: '13º BPM', rank: 'CAP', matricula: '98653261', name: 'EVERTON ESTEVAN CABRAL DA SILVA', role: 'Subcomandante do 13º BPM', contact: '98746-0490' },
  { id: 'esp-4', category: 'Especializado', unit: 'BPA', rank: 'MAJ', matricula: '.', name: 'FABIO DE OLIVEIRA CHAVES', role: 'Subcomandante do BPA', contact: '988310639' },
  { id: 'dir-1', category: 'Diretorias', unit: 'DF', rank: 'CEL', matricula: '116564', name: 'FERNANDO GLAUCIO SANTOS LIMA', role: 'Diretor de Finanças', contact: '99973-6460' },
  { id: 'sul-1', category: 'Sul', unit: 'CPRSul', rank: 'TC', matricula: '1207083', name: 'FERNANDO JOSE FERREIRA SOARES JUNIOR', role: 'Comandante do Comando de Policiamento da Região Sul', contact: '98866-2298' },
  { id: 'mis-11', category: 'Missões', unit: 'CPChoque', rank: 'CAP', matricula: '1449', name: 'FILLIPE ALMEIDA DE ARAUJO', role: 'Comandante da CPChoque', contact: '98867-4262' },
  { id: 'm-20', category: 'Metropolitana', unit: '5ª CPM/I', rank: 'CAP', matricula: '1203495', name: 'FRANCISCO LUTIANE DE BRITTO', role: 'Comandante da 5ª CPM/I – Antares. (NOVO)', contact: '988366853' },
  { id: 'nzm-6', category: 'Norte/ZM', unit: '6º BPM', rank: 'CAP', matricula: '98656554', name: 'FRANKLIN MELO DOS SANTOS', role: 'Subcomandante do 6º BPM', contact: '99373-1991' },
  { id: 'dir-14', category: 'Diretorias', unit: 'CFAP', rank: 'MAJ', matricula: '1207172', name: 'GEISON FRANCA DA SILVA', role: 'Subcomandante do CFAP', contact: '98837-5244' },
  { id: 'cg-10', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'TC', matricula: '114022', name: 'GERILO ALVES DE OLIVEIRA', role: 'Chefe da Ajudância Geral', contact: '99142-4292' },
  { id: 'esp-6', category: 'Especializado', unit: 'BPTran', rank: 'MAJ', matricula: '1423916', name: 'GILVANO SILVA SANTOS JUNIOR', role: 'Subcomandante do BPTran', contact: '98861-6675' },
  { id: 'nzm-3', category: 'Norte/ZM', unit: '2º BPM', rank: 'MAJ', matricula: '1207369', name: 'GLAUBER PATRICK DE SANTANA SANTOS', role: 'Comandante do 2º BPM – União dos Palmares', contact: '99662-0121' },
  { id: 'dir-4', category: 'Diretorias', unit: 'PMAL', rank: 'TC', matricula: '117498', name: 'GLAUCO PAES TORRES', role: 'Subdiretor de Pessoal c/c Chefe do Centro de Segurança Individualizada (CSI) da Diretoria de Pessoal', contact: '99997-3549' },
  { id: 'm-5', category: 'Metropolitana', unit: '4º BPM', rank: 'MAJ', matricula: '121045', name: 'GLAUDSON JATOBA DE OLIVEIRA', role: 'Comandante do 4º BPM – Farol', contact: '99924-7832' },
  { id: 'm-4', category: 'Metropolitana', unit: '1º BPM', rank: 'CAP', matricula: '98653156', name: 'GRAYSON SAMUEL DA SILVA', role: 'Subcomandante 1º BPM', contact: '99909-2937' },
  { id: 'esp-5', category: 'Especializado', unit: 'BPTran', rank: 'TC', matricula: '117625', name: 'HARLEN LOPES MENDES', role: 'Comandante do BPTran', contact: '99835-4510' },
  { id: 'ser-3', category: 'Sertão', unit: '7º BPM', rank: 'TC', matricula: '102717', name: 'HEBERT ALEKSANDER CARVALHO DE SANTANA', role: 'Comandante do 7º BPM – Santana do Ipanema', contact: '99974-7222' },
  { id: 'mis-5', category: 'Missões', unit: 'ROTAM', rank: 'MAJ', matricula: '1207342', name: 'HELQUIAS ALISSON SANTOS PEREIRA', role: 'Comandante da ROTAM', contact: '98831-8546' },
  { id: 'dir-12', category: 'Diretorias', unit: 'APMSAM', rank: 'TC', matricula: '117579', name: 'HELSON DE AZEVEDO SOUZA NETO', role: 'Subcomandante da APMSAM', contact: '99644-2161' },
  { id: 'mis-1', category: 'Missões', unit: 'CME', rank: 'TC', matricula: '120707', name: 'HENRIQUE JATOBÁ CORREIA', role: 'Comandante do Comando de Missões Especiais', contact: '98885-9474' },
  { id: 'm-1', category: 'Metropolitana', unit: 'CPM', rank: 'TC', matricula: '120812', name: 'HIRAQUE AGNNES DOS SANTOS', role: 'Comandante do Policiamento Metropolitano', contact: '98858-9137' },
  { id: 'cg-11', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'CAP', matricula: '1554', name: 'IGOR SARMENTO FIRMINO', role: 'Subchefe da Assessoria do Subcomandante Geral', contact: '99953-3113' },
  { id: 'agr-9', category: 'Agreste', unit: '7ª CPM/I', rank: 'MAJ', matricula: '1200593', name: 'JACKSON PEDRO DOS SANTOS LINO', role: 'Comandante da 7ª CPM/I – Girau do Ponciano', contact: '98117-8949' },
  { id: 'ser-8', category: 'Sertão', unit: '6ª CPM/I', rank: '1º TEN', matricula: '44261', name: 'JAILSON COSTA DE LIMA', role: 'Subcomandante da 6ª CPM/I –', contact: '99905-6401' },
  { id: 'm-11', category: 'Metropolitana', unit: '12º BPM', rank: 'TC', matricula: '1201204', name: 'JASIEL FRANCISCO SILVA DE ANDRADE', role: 'Comandante do 12º BPM - Cidade Universitária', contact: '99992-8377' },
  { id: 'sul-4', category: 'Sul', unit: '11º BPM', rank: 'MAJ', matricula: '1206656', name: 'JEAN MIGUEL DA SILVA', role: 'Subcomandante do 11º BPM', contact: '99964-0891' },
  { id: 'm-10', category: 'Metropolitana', unit: '8º BPM', rank: 'CAP', matricula: '332151', name: 'JEFFERSON CARUZO FERREIRA', role: 'Subcomandante do 8º BPM', contact: '98766-9222' },
  { id: 'dir-22', category: 'Diretorias', unit: 'DS', rank: 'TC', matricula: '113530', name: 'JEFFERSON LUIZ TAVARES DA SILVA', role: 'CIA', contact: '99647-5758' },
  { id: 'sul-3', category: 'Sul', unit: '11º BPM', rank: 'MAJ', matricula: '1200720', name: 'JERCIO TEIXEIRA DE FARIAS', role: 'Comandante do 11º BPM – Penedo', contact: '99629-0028' },
  { id: 'mis-4', category: 'Missões', unit: 'BOPE', rank: 'MAJ', matricula: '98667831', name: 'JOACY GALDINO DA SILVA JUNIOR', role: 'Subcomandante do BOPE', contact: '98811-1016' },
  { id: 'dir-17', category: 'Diretorias', unit: 'DPP', rank: 'TC', matricula: '102652', name: 'JORGE FRANCELINO TENORIO', role: 'Subdiretor de Políticas Preventivas', contact: '98833-4156' },
  { id: 'emg-5', category: 'EMG', unit: 'EMG', rank: 'TC', matricula: '113301', name: 'JORGE RODRIGUES DE MORAIS JUNIOR', role: 'Chefe da 3ª Seção do EMG', contact: '99125-0056' },
  { id: 'cg-13', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'MAJ', matricula: '1207547', name: 'JOSE ANDERSON BOMFIM BARROS', role: 'Chefe da Seção de Atendimento ao Público da Ouvidoria Geral', contact: '999220496' },
  { id: 'esp-2', category: 'Especializado', unit: 'CPE', rank: 'TC', matricula: '117765', name: 'JOSE BARBOSA SILVA JUNIOR', role: 'Subcomandante do Policiamento Especializado', contact: '99690-0766' },
  { id: 'cor-1', category: 'Administrativo', unit: 'CORREG', rank: 'TC', matricula: '117773', name: 'JOSÉ DANIEL DE LIMA NETO', role: 'Corregedor Geral', contact: '98848-4560' },
  { id: 'mis-12', category: 'Missões', unit: 'CPChoque', rank: '1º TEN', matricula: '44288', name: 'JOSE FERNANDO DE OLIVEIRA CIRILO FILHO', role: 'Subcomandante da CPChoque', contact: '99304-3635' },
  { id: 'm-16', category: 'Metropolitana', unit: '2ª CPM/I', rank: 'CAP', matricula: '98653059', name: 'JOSE PEDRO DOS ANJOS SILVA', role: 'Comandante da 2ª CPM/I –Paripueira', contact: '98876-8896' },
  { id: 'emg-6', category: 'EMG', unit: 'EMG', rank: 'MAJ', matricula: '116858', name: 'JOSE PETRONIO PANTALEAO DOS SANTOS', role: 'Chefe da 4ª Seção do EMG', contact: '99691-1953' },
  { id: 'agr-10', category: 'Agreste', unit: '7ª CPM/I', rank: 'CAP', matricula: '1708', name: 'JOSE SALATIEL COSTA BEZERRA', role: 'Subcomandante da 7ª CPM/I', contact: '99950-1916' },
  { id: 'dir-19', category: 'Diretorias', unit: 'DPS', rank: 'TC', matricula: '120928', name: 'JOSILEIDE ROMEIRO MELO DE CASTRO', role: 'Subdiretor de Proteção Social c/c Chefe da Seção de Cadastro e Arquivamento da Diretoria de Proteção Social', contact: '988396426' },
  { id: 'dir-8', category: 'Diretorias', unit: 'PMAL', rank: 'MAJ', matricula: '1206710', name: 'JOSUÉ DOS SANTOS SOUZA ELIZIÁRIO', role: 'Subdiretor de Inteligência', contact: '99801-5521' },
  { id: 'm-12', category: 'Metropolitana', unit: '12º BPM', rank: 'CAP', matricula: '000051', name: 'KELMANY MARCIO DE ASSIS SILVA', role: 'Subcomandante do 12º BPM', contact: '98884-4455' },
  { id: 'cg-9', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'TC', matricula: '102750', name: 'LUCIANA LEITE SARMENTO', role: 'Chefe da Ouvidoria Geral', contact: '99341-0407' },
  { id: 'esc-5', category: 'Diretorias', unit: 'CPM-Int', rank: 'TC', matricula: '117668', name: 'LUCIANO FELIZARDO DOS SANTOS', role: 'Comandante do Colégio da Polícia Militar do Interior', contact: '99933-2773' },
  { id: 'm-7', category: 'Metropolitana', unit: '5º BPM', rank: 'TC', matricula: '547913', name: 'LUCIANO JOAO DA SILVA', role: 'Comandante do 5º BPM - Benedito Bentes', contact: '98891-2642' },
  { id: 'sul-5', category: 'Sul', unit: '1ª CPM/I', rank: 'CAP', matricula: '98667874', name: 'LUIZ FELIPE DE OLIVEIRA ROCHA UGA CAMARA', role: 'Comandante da 1ª CPM/I – São Miguel dos Campos', contact: '99116-2198' },
  { id: 'esp-12', category: 'Especializado', unit: 'CPM/I-Faz', rank: '1º TEN', matricula: '22772', name: 'LUIZ FERNANDO FRANÇA DE ARAUJO', role: 'Subcomandante da CPM/I-Faz', contact: '99836-4270' },
  { id: 'nzm-9', category: 'Norte/ZM', unit: '8ª CPM/I', rank: 'MAJ', matricula: '1206877', name: 'LUIZ GONZAGA DE MELO FILHO', role: 'Comandante da 8ª CPM/I – São Luís do Quitunde', contact: '99920-9405' },
  { id: 'm-3', category: 'Metropolitana', unit: '1º BPM', rank: 'TC', matricula: '113557', name: 'LUIZ SANTOS DA SILVA', role: 'Comandante 1º BPM – Vergel do Lago', contact: '98878-2458' },
  { id: 'cg-8', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'TC', matricula: '120456', name: 'MARCELO FERREIRA LIMA VALOES', role: 'Chefe da Assessoria do Subcomandante Geral', contact: '98894-1958' },
  { id: 'sul-7', category: 'Sul', unit: '9ª CPM/I', rank: 'MAJ', matricula: '1200488', name: 'MARCOS AURELIO RIBEIRO PEREIRA', role: 'Comandante da 9ª CPM/I – Coruripe; (NOVO)', contact: '99629-2938' },
  { id: 'ser-6', category: 'Sertão', unit: '9º BPM', rank: 'CAP', matricula: '1207490', name: 'MARCUS VINICIUS SILVA CAVALCANTE', role: 'Subcomandante do 9º BPM', contact: '996719192' },
  { id: 'sul-2', category: 'Sul', unit: 'CPRSul', rank: 'TC', matricula: '1206788', name: 'MARIA ADRIANA DE SOUZA', role: 'SubComandante do Comando de Policiamento da Região Sul', contact: '99607-4022' },
  { id: 'cg-12', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'CAP', matricula: '423983', name: 'MARIANA CESAR GOIS CAETANO TOLEDO', role: 'Subchefe da Ajudância Geral c/c Chefe da Secretaria da Ajudância Geral', contact: '99610-6162' },
  { id: 'esp-1', category: 'Especializado', unit: 'CPE', rank: 'CEL', matricula: '117560', name: 'MARIO ANTONIO DE OLIVEIRA XAVIER', role: 'Comandante do Policiamento Especializado', contact: '98151-1329' },
  { id: 'nzm-1', category: 'Norte/ZM', unit: 'CPRN-ZM', rank: 'CEL', matricula: '113611', name: 'MARLON BATISTA DE ARAUJO', role: 'Comandante do Policiamento da Região Norte e Zona da Mata', contact: '99991-3314' },
  { id: 'sul-6', category: 'Sul', unit: '1ª CPM/I', rank: 'CAP', matricula: '5819', name: 'MAXSUEL SANTOS SILVA', role: 'Subcomandante da 1ª CPM/I', contact: '99933-2270' },
  { id: 'm-18', category: 'Metropolitana', unit: '4ª CPM/I', rank: 'CAP', matricula: '498513', name: 'MICHEL LINS PIMENTEL', role: 'Comandante da 4ª CPM/I – Marechal Deodoro', contact: '99933-0593' },
  { id: 'mis-9', category: 'Missões', unit: 'COPES', rank: 'MAJ', matricula: '1207229', name: 'MIGUEL VIEIRA DOS SANTOS NETO', role: 'Comandante da COPES', contact: '99630-8899' },
  { id: 'dir-10', category: 'Diretorias', unit: 'PMAL', rank: 'TC', matricula: '121096', name: 'MIZAEL LEITE PESSOA JUNIOR', role: 'Subdiretor de Comunicação Social', contact: '98805-2920' },
  { id: 'cg-7', category: 'Subcomando', unit: 'Subcomando Geral', rank: 'CEL', matricula: '101621', name: 'NEYVALDO JOSÉ AMORIM DA SILVA', role: 'SubComandante Geral', contact: '99942-6194' },
  { id: 'dir-16', category: 'Diretorias', unit: 'DPP', rank: 'CEL', matricula: '113271', name: 'NILTON ROCHA JUNIOR', role: 'Diretor de Políticas Preventivas', contact: '99818-9596' },
  { id: 'esp-9', category: 'Especializado', unit: 'BPEsc', rank: 'MAJ', matricula: '120944', name: 'NOEMI GOMES FIRMO SOARES', role: 'Comandante do BPEsc', contact: '99430-7032' },
  { id: 'cg-1', category: 'Comando', unit: 'GCG', rank: 'CEL', matricula: '---', name: 'PAULO AMORIM FEITOSA FILHO', role: 'Comandante Geral', contact: '98109-8500' },
  { id: 'ser-4', category: 'Sertão', unit: '7º BPM', rank: 'CAP', matricula: '1287', name: 'PAULO CEZAR SOARES DA SILVA JUNIOR', role: 'Subcomandante do 7º BPM', contact: '98133-3695' },
  { id: 'emg-4', category: 'EMG', unit: 'EMG', rank: 'TC', matricula: '87270', name: 'PAULO EUGENIO DA SILVA FREITAS', role: 'Chefe da 2ª Seção do EMG', contact: '98810-5721' },
  { id: 'm-21', category: 'Metropolitana', unit: '5ª CPM/I', rank: 'CAP', matricula: '18864', name: 'PAULO VICTOR DE LIMA RODRIGUES', role: 'Subcomandante da 5ª CPM/I', contact: '99939-1155' },
  { id: 'ser-5', category: 'Sertão', unit: '9º BPM', rank: 'TC', matricula: '14575', name: 'PEDRO BARBOSA DE OLIVEIRA JUNIOR', role: 'Comandante do 9º BPM - Delmiro Gouveia', contact: '99659-6362' },
  { id: 'dir-15', category: 'Diretorias', unit: 'DEF', rank: 'TC', matricula: '98654160', name: 'PEDRO HENRIQUE BASILIO HONORATO', role: 'Chefe do Departamento de Educação Física', contact: '98840-1041' },
  { id: 'esc-1', category: 'Diretorias', unit: 'DEIP', rank: 'CEL', matricula: '427705', name: 'PEDRO JORGE BUARQUE MOURA', role: 'Diretor de Ensino, Instrução e Pesquisa', contact: '99949-7717' },
  { id: 'dir-3', category: 'Diretorias', unit: 'DP', rank: 'TC', matricula: '117552', name: 'PHELIPE ROGERIO DOS SANTOS', role: 'Diretor de Pessoal', contact: '98807-1211' },
  { id: 'ser-1', category: 'Sertão', unit: 'CPRS', rank: 'CEL', matricula: '101753', name: 'RAIMUNDO JOSE DE FREITAS LESSA', role: 'Comandante do Comando de Policiamento da Região Sertão', contact: '99982-4907' },
  { id: 'mis-10', category: 'Missões', unit: 'COPES', rank: 'CAP', matricula: '01651', name: 'RAMON DA SILVA RIBEIRO', role: 'Subcomandante da COPES', contact: '99671-0487' },
  { id: 'sul-8', category: 'Sul', unit: '9ª CPM/I', rank: '1º TEN', matricula: '10669', name: 'RENATO BATISTA SANTOS', role: 'Subcomandante da 9ª CPM/I', contact: '9935-5811' },
  { id: 'dir-5', category: 'Diretorias', unit: 'DLog', rank: 'CEL', matricula: '113972', name: 'RENILSON RODRIGUES DANTAS', role: 'Diretor de Logística', contact: '98707-5072' },
  { id: 'dir-6', category: 'Diretorias', unit: 'PMAL', rank: 'TC', matricula: '117803', name: 'ROBERTO FELICIANO COSTA DA SILVA', role: 'Subdiretor de Logística c/c Chefe da Seção de Suprimento (DLog/1) da Diretoria de Logística', contact: '99125-4328' },
  { id: 'agr-7', category: 'Agreste', unit: '3ª CPM/I', rank: 'CAP', matricula: '498882', name: 'RODOLPHO HAMUL DE MELO MARINHO', role: 'Comandante da 3ª CPM/I – Atalaia', contact: '99829-2144' },
  { id: 'sul-10', category: 'Sul', unit: '10ª CPM/I', rank: 'CAP', matricula: '14621', name: 'RODRIGO BARBOSA FERRO', role: 'Subcomandante da 10ª CPM/I', contact: '99602-1188' },
  { id: 'esc-4', category: 'Diretorias', unit: 'CPM-Cap', rank: 'MAJ', matricula: '121118', name: 'RODRIGO MEDEIROS FERREIRA', role: 'Subcomandante do Colégio da Polícia Militar da Capital', contact: '98861-0206' },
  { id: 'm-9', category: 'Metropolitana', unit: '8º BPM', rank: 'MAJ', matricula: '1206567', name: 'RODRIGO VITAL VELOSO SOARES BOTELHO', role: 'Comandante do 8º BPM – Rio Largo', contact: '99630-5904' },
  { id: 'esp-10', category: 'Especializado', unit: 'BPEsc', rank: 'MAJ', matricula: '1200500', name: 'SAMUEL CRUZ DA COSTA', role: 'Subcomandante do BPEsc', contact: '9969-2618' },
  { id: 'agr-6', category: 'Agreste', unit: '10º BPM', rank: 'CAP', matricula: '498734', name: 'SAMUEL DE JESUS TELES', role: 'Subcomandante do 10º BPM', contact: '99935-9381' },
  { id: 'cg-3', category: 'Comando', unit: 'GCG', rank: 'TC', matricula: '114111', name: 'SANDRO RICARDO DOS SANTOS', role: 'Chefe do Núcleo de Qualidade de Vida', contact: '98829-5540' },
  { id: 'mis-6', category: 'Missões', unit: 'ROTAM', rank: 'CAP', matricula: '1562', name: 'SEBASTIAO GRANGEIRO BISNETO', role: 'Subcomandante da ROTAM', contact: '98713-6141' },
  { id: 'emg-2', category: 'EMG', unit: 'EMG', rank: 'TC', matricula: '117820', name: 'SERGIO HENRIQUE LIMA DOS SANTOS', role: 'Subchefe do EMG', contact: '98702-0846' },
  { id: 'esc-3', category: 'Diretorias', unit: 'CPM-Cap', rank: 'TC', matricula: '120995', name: 'SIDNEY INACIO CUNHA', role: 'Comandante do Colégio da Polícia Militar da Capital', contact: '98860-9550' },
  { id: 'emg-7', category: 'EMG', unit: 'EMG', rank: 'TC', matricula: '113212', name: 'SIDRAITON SOARES SANTOS', role: 'Chefe da 5ª Seção do EMG', contact: '98830-3319' },
  { id: 'esp-3', category: 'Especializado', unit: 'BPA', rank: 'TC', matricula: '120060-7', name: 'SILVIO CÉSAR DA SILVA NUNES', role: 'Comandante do BPA', contact: '98863-1542' },
  { id: 'dir-20', category: 'Diretorias', unit: 'DS', rank: 'CEL', matricula: '109282', name: 'SILVIO DE BRITO MOURA', role: 'Diretor de Saúde', contact: '99992-6556' },
  { id: 'dir-9', category: 'Diretorias', unit: 'DCS', rank: 'TC', matricula: '117838', name: 'SILVIO JOSE LUCIO E SILVA', role: 'Diretor de Comunicação Social', contact: '98897-2979' },
  { id: 'dir-21', category: 'Diretorias', unit: 'DS', rank: 'CEL', matricula: '296899', name: 'SIMUR MENDES LAGES MAIA FERREIRA', role: 'Subdiretor de Saúde', contact: '98898-2667' },
  { id: 'esp-7', category: 'Especializado', unit: 'BPRv', rank: 'TC', matricula: '120642', name: 'THALVANNES JOSE BELEM RAMOS', role: 'Comandante do BPRv', contact: '98139-3227' },
  { id: 'dir-18', category: 'Diretorias', unit: 'DPS', rank: 'TC', matricula: '117846', name: 'THAYRONILSON EMERY DOS SANTOS', role: 'Diretor de Proteção Social', contact: '98825-9120' },
  { id: 'mis-14', category: 'Missões', unit: 'CPM/I-RAIO', rank: '1º TEN', matricula: '5614', name: 'THIAGO BRANDAO DE LEMOS INACIO', role: 'Subcomandante da CPM/I-RAIO', contact: '99994-3400' },
  { id: 'dir-7', category: 'Diretorias', unit: 'DI', rank: 'TC', matricula: '1200526', name: 'THIAGO DE MORAES DUARTE OLIVEIRA', role: 'Diretor de Inteligência', contact: '98882-1703' },
  { id: 'nzm-4', category: 'Norte/ZM', unit: '2º BPM', rank: 'CAP', matricula: '1207598', name: 'VICENTE NASCIMENTO NETO', role: 'Subcomandante do 2º BPM', contact: '99687-7817' },
  { id: 'esp-11', category: 'Especializado', unit: 'CPM/I-Faz', rank: 'CAP', matricula: '98667890', name: 'VICTOR SANTOS LOPES SAMPAIO', role: 'Comandante da CPM/I-Faz', contact: '99621-0887' },
  { id: 'm-8', category: 'Metropolitana', unit: '5º BPM', rank: 'CAP', matricula: '14656', name: 'WELLINGTON DOS ANJOS SILVA JUNIOR', role: 'Subcomandante do 5º BPM', contact: '98896-6280' },
  { id: 'm-6', category: 'Metropolitana', unit: '4º BPM', rank: 'CAP', matricula: '1207504', name: 'WENDERSON VIANA GUILHERME', role: 'Subcomadante do 4º BPM', contact: '98810-1060' },
];

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'Todos os Contatos',
  Comando: 'Comando Geral',
  Subcomando: 'Subcomando Geral',
  EMG: 'Estado Maior Geral',
  Metropolitana: 'Região Metropolitana',
  Sertão: 'Região Sertão',
  Agreste: 'Região Agreste',
  'Norte/ZM': 'Região Norte / ZM',
  Sul: 'Região Sul',
  Especializado: 'Pol. Especializado',
  Missões: 'Missões Especiais',
  Diretorias: 'Diretorias / Ensino',
  Administrativo: 'Corregedoria'
};
